using Microsoft.IdentityModel.Tokens;
using SafeVault.Models;
using System.IdentityModel.Tokens.Jwt;
using System.Security.Claims;
using System.Text;

namespace SafeVault.Services;

/// <summary>
/// Interface for JWT token generation and validation.
/// </summary>
public interface IJwtService
{
      string GenerateToken(ApplicationUser user, IList<string> roles);
      ClaimsPrincipal? ValidateToken(string token);
      string GenerateRefreshToken();
}

/// <summary>
/// JWT Service implementing secure token generation and validation.
/// 
/// SECURITY BEST PRACTICES IMPLEMENTED (with Copilot assistance):
/// - Short token expiration (15 minutes for access tokens)
/// - Refresh token rotation
/// - Claim-based identity
/// - Cryptographically strong signing keys
/// - Token revocation via refresh token tracking
/// </summary>
public class JwtService : IJwtService
{
    private readonly IConfiguration _configuration;
        private readonly string _secretKey;
            private readonly string _issuer;
                private readonly string _audience;
                    private readonly int _expirationMinutes;

                        public JwtService(IConfiguration configuration)
                            {
                                    _configuration = configuration;
                                            var jwtSettings = _configuration.GetSection("JwtSettings");
                                                    _secretKey = jwtSettings["SecretKey"] ?? throw new InvalidOperationException("JWT SecretKey not configured");
                                                            _issuer = jwtSettings["Issuer"] ?? "SafeVault";
                                                                    _audience = jwtSettings["Audience"] ?? "SafeVaultUsers";
                                                                            _expirationMinutes = int.Parse(jwtSettings["ExpirationMinutes"] ?? "15");
                                                                                }

                                                                                    /// <summary>
                                                                                        /// Generates a JWT token with user claims and roles.
                                                                                            /// Implements principle of least privilege via role-based claims.
                                                                                                /// </summary>
                                                                                                    public string GenerateToken(ApplicationUser user, IList<string> roles)
                                                                                                        {
                                                                                                                var tokenHandler = new JwtSecurityTokenHandler();
                                                                                                                        var key = Encoding.UTF8.GetBytes(_secretKey);
                                                                                                                        
                                                                                                                                var claims = new List<Claim>
                                                                                                                                        {
                                                                                                                                                    new(ClaimTypes.NameIdentifier, user.Id),
                                                                                                                                                                new(ClaimTypes.Email, user.Email ?? string.Empty),
                                                                                                                                                                            new(ClaimTypes.Name, user.UserName ?? string.Empty),
                                                                                                                                                                                        new("first_name", user.FirstName),
                                                                                                                                                                                                    new("last_name", user.LastName),
                                                                                                                                                                                                                new(JwtRegisteredClaimNames.Jti, Guid.NewGuid().ToString()),
                                                                                                                                                                                                                            new(JwtRegisteredClaimNames.Iat,
                                                                                                                                                                                                                                            DateTimeOffset.UtcNow.ToUnixTimeSeconds().ToString(),
                                                                                                                                                                                                                                                            ClaimValueTypes.Integer64)
                                                                                                                                                                                                                                                                    };
                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                            // Add role claims for RBAC
                                                                                                                                                                                                                                                                                    foreach (var role in roles)
                                                                                                                                                                                                                                                                                            {
                                                                                                                                                                                                                                                                                                        claims.Add(new Claim(ClaimTypes.Role, role));
                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                        var tokenDescriptor = new SecurityTokenDescriptor
                                                                                                                                                                                                                                                                                                                                {
                                                                                                                                                                                                                                                                                                                                            Subject = new ClaimsIdentity(claims),
                                                                                                                                                                                                                                                                                                                                                        Expires = DateTime.UtcNow.AddMinutes(_expirationMinutes),
                                                                                                                                                                                                                                                                                                                                                                    Issuer = _issuer,
                                                                                                                                                                                                                                                                                                                                                                                Audience = _audience,
                                                                                                                                                                                                                                                                                                                                                                                            SigningCredentials = new SigningCredentials(
                                                                                                                                                                                                                                                                                                                                                                                                            new SymmetricSecurityKey(key),
                                                                                                                                                                                                                                                                                                                                                                                                                            SecurityAlgorithms.HmacSha256Signature)
                                                                                                                                                                                                                                                                                                                                                                                                                                    };
                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                            var token = tokenHandler.CreateToken(tokenDescriptor);
                                                                                                                                                                                                                                                                                                                                                                                                                                                    return tokenHandler.WriteToken(token);
                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                            /// <summary>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                /// Validates a JWT token and returns the claims principal.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    /// Returns null if token is invalid.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        /// </summary>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            public ClaimsPrincipal? ValidateToken(string token)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if (string.IsNullOrEmpty(token)) return null;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                try
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    var tokenHandler = new JwtSecurityTokenHandler();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                var key = Encoding.UTF8.GetBytes(_secretKey);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            var validationParameters = new TokenValidationParameters
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ValidateIssuerSigningKey = true,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        IssuerSigningKey = new SymmetricSecurityKey(key),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ValidateIssuer = true,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ValidIssuer = _issuer,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ValidateAudience = true,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ValidAudience = _audience,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ValidateLifetime = true,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ClockSkew = TimeSpan.Zero // Strict expiration
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                var principal = tokenHandler.ValidateToken(token, validationParameters, out _);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return principal;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            catch (SecurityTokenException)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return null;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                /// <summary>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    /// Generates a cryptographically random refresh token.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        /// </summary>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            public string GenerateRefreshToken()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        var randomBytes = new byte[64];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                using var rng = System.Security.Cryptography.RandomNumberGenerator.Create();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        rng.GetBytes(randomBytes);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return Convert.ToBase64String(randomBytes);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
